### ISSUE TITLE
Failed to Start Minecraft: Solve Method First

### ISSUE THREAD

**Issue by ghost** [ModsByLeo/SpeedTrading#1]
Creating this issue to figure out whats going on I'll be post updates in this issue thread until the problem is resolved. You noted that it might not be your mod and it could just be fabric loader but Its only when I use this mod that I have this issue with.

This is the error code I get 
```
[15:31:02] [main/INFO]: Loading for game Minecraft 1.16.1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsupportedOperationException: Call the solve method first!!!
    at net.fabricmc.loader.util.sat4j.minisat.core.Solver.model(Solver.java:498)
    at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:223)
    at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:604)
    at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:202)
    at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    ... 8 more
Exiting with -1
Process exited with code -1.
```
![Screenshot_22](https://user-images.githubusercontent.com/36317465/90557899-3843bb00-e169-11ea-985e-70c1af2a6b6a.png)

Here is a screenshot of my friend having the same issue. He also only has FabricAPI and SpeedTrading installed

**Comment by ghost** [comment]
So it seems that using an older version(v1.1.0) of the mod works fine and doesn't have this issue. I don't know why the version for 1.16.2 doesn't work for 1.16.1, but there are features in the updated version of the mod that is very handy, and I wish that I had, but I assume this won't matter once the server that I play on updates to 1.16.2 which is just waiting on PaperMC to update to 1.16.2

**Comment by Leo40Git** [comment]
I'm not 100% sure if a version for 1.16.2 would work for 1.16.1, but it should at least let you *launch the game*.
Unfortunately, I have no idea how to solve this, or even if I *can* solve this...

**Comment by Leo40Git** [comment]
Nobody else has reported this, so...
